fixed bug where empty summaries fail with index error
DanielNoord/pydocstringformatter pull request #163
Opened 2022-09-10 21:50 UTC by jspaezp

Discussed in the second section of:

https://github.com/DanielNoord/pydocstringformatter/issues/160

2022-09-11 05:27 UTC, Pierre-Sassoulas approved these changes

2022-09-12 07:32 UTC, DanielNoord requested changes

2022-09-12 07:32 UTC, DanielNoord commented on pydocstringformatter/_formatting/formatters_default.py
> +        if len(summary_lines) < 1:
```suggestion
        if not summary_lines:
```

2022-09-12 07:32 UTC, DanielNoord approved these changes

2022-09-12 07:33 UTC, DanielNoord commented on pydocstringformatter/_formatting/formatters_default.py
> +            summary_lines = [""]
```suggestion
        if not (summary_lines := summary.splitlines()):
            summary_lines = [""]
```

2022-09-12 07:33 UTC, DanielNoord approved these changes

2022-09-12 07:36 UTC, merged