Make ``SplitSummaryAndDocstringFormatter`` non-optional
DanielNoord/pydocstringformatter pull request #94
Opened 2022-04-28 12:20 UTC by DanielNoord

Closes #68.

Best viewed commit per commit. Sadly had to update a lot of test outputs as they do not adhere to the formatting of this checker.

2022-04-28 12:34 UTC, DanielNoord commented
@Pierre-Sassoulas Note that the primer is a little trigger happy as we don't run with any commands. Since we have ``max-summary-lines=2`` and the default being 1, it seems like a lot will change. But the changes are minimal.

2022-04-28 12:44 UTC, Pierre-Sassoulas commented
For thing like :
```diff
-    """Get values listed in <columns> from <stats> and <old_stats>,
+    """Get values listed in <columns> from <stats> and <old_stats>,.
```
We could maybe replace the ``,`` by a ``.`` instead ?

2022-04-28 12:45 UTC, DanielNoord commented
> For thing like :
> 
> ```diff
> -    """Get values listed in <columns> from <stats> and <old_stats>,
> +    """Get values listed in <columns> from <stats> and <old_stats>,.
> ```
> 
> We could maybe replace the `,` by a `.` instead ?

I thought about this, but then decided it was probably best to let the user decide whether they want to break the sentence there or not. Just replacing `,` with `.` might not always work so some user-input will always be needed.

2022-05-01 22:05 UTC, Pierre-Sassoulas requested changes

2022-05-01 22:05 UTC, Pierre-Sassoulas commented on docs/usage.rst
> +                            existing projects. (default: True)
```suggestion
                            with the --max-summary-lines option. (default: True)
```

2022-05-02 06:50 UTC, merged